language: rust
rust:
  - stable
  # - beta
  # - nightly
cache: cargo
# jobs:
#   allow_failures:
#     - rust: nightly
#   fast_finish: true
before_script: cd rs-landmark
script:
  - cargo build --verbose --all-targets
  - cargo test --verbose --all